name: build_check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pod install
      run: pod install --project-directory=Example --repo-update
    - name: Run test
      run: set -o pipefail && xcodebuild -workspace Example/RxAlertViewable.xcworkspace -scheme RxAlertViewable -sdk iphonesimulator build CODE_SIGNING_REQUIRED=NO | xcpretty -c
